version: '3'
services:

    app:
        build: ./client
        restart: always
        volumes:
            - .:/usr/src/app
        # ports:
        #     - 9998:8080
        environment:
            - FLASK_APP=./app/__init__.py
            - FLASK_ENV=production
            - APP_SETTINGS=app.config.ProductionConfig
        volumes:
            - ./client:/app
            - /etc/localtime:/etc/localtime:ro
            - ./client/logs:/app/logs
        expose:
            - 8080

    nginx:
        build: ./nginx
        container_name: nginx
        restart: always
        volumes:
            - ./client/app/static:/usr/src/app/project/static
        ports:
            - "80:80"